### ISSUE TITLE
Fade while switching inconsistent initial values

### ISSUE THREAD

**Issue by patheros** [alefnull/NullPath#2]
On Expand and Collapse this starts ON but one Entangle it starts OFF. Feels like they should be the same to me.

**Comment by alefnull** [comment]
fixed with [bd73d0446bcf0f6a489377c8eeedde0e9db2ad04](https://github.com/alefnull/NullPath/commit/bd73d0446bcf0f6a489377c8eeedde0e9db2ad04)
