### ISSUE TITLE
Entangle Mode, Entropy and Chan CV to Trigger

### ISSUE THREAD

**Issue by patheros** [alefnull/NullPath#3]
Feature Request: Have a right click option that turns these into triggers instead of CVs. When triggers each high transition would cycle to the next mode.

**Comment by alefnull** [comment]
implemented with [700c507c4b8967e4f61a742d8b66277f0f7fd8d2](https://github.com/alefnull/NullPath/commit/700c507c4b8967e4f61a742d8b66277f0f7fd8d2)
