### ISSUE TITLE
Turbulence may temporarily fall silent when using very short gates and very short envelopes self patched to modulate pitch.

### ISSUE THREAD

**Issue by Kwurqx** [alefnull/NullPath#6]
Since Turbulence offers
- (a mix of) various waveshapes
- noise (with duration and level control)
- pitch control (via v/Oct)
- gates of various lengths via the Gate input
- an ADSR....

I thought is was a nice "extreme" test to see if I could use Turbulence as a Kick/Snare. This involved very short gates, very short envelopes and the envelope out self patched to V/Oct causing very fast and wide ranged pitch modulation (sweep). I noticed that at some point Turbulence, while happily generating a sort of distorted kick/snare, sometimes suddenly falls silent, then skips some gates/triggers, and after that, happily continues producing sounds.

BTW I also routed the env out via Oct to V/Oct in to offset the envelope. But the cause is in the env out which at some points no longer changed output values for some period of time.

**Comment by alefnull** [comment]
i'm having trouble replicating this issue. i've turned all four ADSR knobs all the way down for the shortest possible envelope, patched the envelope out into the v/oct input, and have tried sending variable length gates and even just triggers, all at varying rates, and i can't reproduce what you describe as the envelope output failing to recognize some triggers/gates and failing to 'trigger' itself.

can you possibly share the patch you were experiencing this in?

**Comment by Kwurqx** [comment]
I pasted/uploaded "nullpath Turbulence issue#6.vcv" in a zip file. For me, within 10-20 seconds, some gates are missed. Win10pro x64.
[nullpath Turbulence issue#6.zip](https://github.com/alefnull/NullPath/files/10669937/nullpath.Turbulence.issue.6.zip)

**Comment by alefnull** [comment]
strange. i'm not experiencing that at all with this patch. i left it on for a good minute or two, and as far as i could tell, every gate triggered the envelope normally. could you do me a favor and check to see which exact build version you're using?
![image](https://user-images.githubusercontent.com/1663704/217109819-a2fd504d-ffd7-4f57-b852-6a1533ed8912.png)

**Comment by Kwurqx** [comment]
From copy/pasted json
      "version": "2.0.0-bf523fa",

For me it's behaving as described. I do notice a pattern. It works for 30 times then skips 10 and repeats this pattern. This is at the current settings as I shared with you. Weird.....

**Comment by alefnull** [comment]
very strange indeed o.O thanks for the details. will continue to look into this as best i can. ¯\_(●_●)_/¯

**Comment by Kwurqx** [comment]
Just tried and noticed: different patterns at different BPM. So....it's TRIGGER related. And yes, I use a TRIGGER to GATE input. This suggests it's some combination of small pulsewidth of the GATE signal and the BPM.

JW Clock outputs TRIGGER (not GATE)

**Comment by Kwurqx** [comment]
I have just put VCV GATES in between JW Clock and Turbulence. So I can adjust the pulsewidth of the GATE. If the pulsewitdth is down to a few milliseconds, strange things start to happen. Not only the periodic skipping at 1 (and a bit) ms, but audible slew like distortion. going upward towards some 30 ms. Beyond that it retriggers.

**Comment by Kwurqx** [comment]
Further troubleshooting/analysis of this weird phenomenon. Reducing variables. Putting VCV Gates in between to control the pulse width. Stripping all modulation, just triggering the gate, I get skipping with very short pulses to the gate input. It's a mystery.

**Comment by alefnull** [comment]
lol i truly, truly appreciate you taking more time to give me more info. i'm STILL unable to replicate the issue even after adding in VCV Gates and trying 1ms all the way up to the max setting, and didn't notice any of what you have described.

even after stripping all modulation, no skips whatsoever.

**Comment by Kwurqx** [comment]
It's way past midnight where I live. Need some sleep...before work in a few hours. Maybe it's in some variables we have not considered. Something to do with timing/resolution. E.g. engine samplerate. I'm running 48 Khz.

**Comment by alefnull** [comment]
nice! that was the difference we were looking for. i had Rack running at 96Khz. i set it to 48 and experienced your original issue immediately. will dig into this tomorrow when i have the time.

**Comment by patheros** [comment]
Should be fixed with the next build.

**Comment by alefnull** [comment]
@Kwurqx try this build. it works at 48 Khz on both mine and Patheros' machines.

https://github.com/alefnull/NullPath/releases/tag/2.0.0-bcb76b0

**Comment by Kwurqx** [comment]
I can confirm that with build 2.0.0-bcb76b0 there are no more 'dropouts' at my side. I also noticed that the minimum Attack and Release times are now 0.001 s (was 0.01 s ? So, 10x faster?). Anyway: no more dropouts! Even at minimum attack/decay. Succes!
