### ISSUE TITLE
Enhancement: Turbulence: add VCA (with modulation input) for the audio output(s)

### ISSUE THREAD

**Issue by Kwurqx** [alefnull/NullPath#8]
Would be great to also have a VCA at  the output(s). Making the Turbulence a more complete synth module. WIth a CVinput you could use the internal ADSR or some external CV control. Even do AM when modulating amplitude at audiorates.

Having attenuverters to route the internal ADSR and/or VCA CV input to individual output VCA's would be great too...

**Comment by alefnull** [comment]
> Having attenuverters to route the internal ADSR and/or VCA CV input to individual output VCA's would be great too...

could you expand a little bit on this? do you mean you want to be able to use the internal envelope or external cv input to modulate the amplitudes of each individual wave in the final mix?

**Comment by Kwurqx** [comment]
I'm sorry for being pretty sloppy in describing this. It was actually intentially ambiguous, leaving a lot of room for interpretation. Mainly on options/scope.

Anyway...

There is an internal ADSR available. That modulation source could be routed to modulate input (generally CV) and/or  output (generally AUDIO) levels...which is generally done with a VCA. So, best case we could have VCA's at inputs and outputs, controlling there in- and output levels. Attenuverters could not only control amplification (Volt * (0 to +1)) but also invert the ADSR curve (or more generally modulation signals) if so desired (Volt * (0 to -1)). And yes, you might even allow the audio signals to be inverted. This does effect the total shape/spectrum in case of a mixed signal.

If we have VCA's at in- and/or outputs, we could of course also have knobs to statically/manually set levels. At the outputs this would effectively be mix levels. At the inputs modulation amounts.

We could also consider to introduce external modulation inputs to control thes VCA's. But...this would not only take up some GUI real-estate, we should also think about behavior. I'd say that DEFAULT the input and output levels would be controled (set) via knobs and optionally (also) by internal ADSR and/or external modulation source (or....selfpatching). If a modulation source is connected the incoming Voltage (could be sum/average if internal+external) could represent a percentage of the value set by the knob (set somewhere between -1 and 1). 

Alternatively the incoming external modulation Voltage could fully override the knob (would then be inconsistent with the internal ADSR that can only do 0 to 1). 

Alternatively you could introduce a modulation matrix, possibly saving GUI element(s), but if so, at the cost of less oversight and direct interaction (a major thing in modular).

As ever there are many, many options. So, its mainly about the Goldilocks principle. At what point is it good enough.
https://en.wikipedia.org/wiki/Goldilocks_principle

In modular it could be that having a lot of fixed correlated functionality packed into one smart compact package is preferred above a constellation of modules and cable latency and clutter that, in totality, might offer similar functionality.

Hope this splat of text contains some clarification and inspiration...

And, yes, I generally don't dwell much on GitHub. Even less logged in. So, mail is a safer bet to get in touch.
