### ISSUE TITLE
Expand not responding to clock

### ISSUE THREAD

**Issue by pizzathehut893** [alefnull/NullPath#9]
Hello!
I'm a big fan of your expand & collapse switches, but I've noticed that while trying to use expand, it doesn't cycle forward when it receives a clock trigger/gate.  Collapse works as intended, so I thought that maybe I'm overlooking a simple error I'm making, or the clock input on expand isn't responding.  If it is an bug, I wanted to know if it's only on my end too.  

Thank you!

**Comment by alefnull** [comment]
hi! thanks so much for checking out the modules and i'm glad you like them.

i haven't actually done any VCV Rack development in quite a long while, and the complexities of fixing issues in NullPath are part of the reason i backed away from it.

that said, however, i just opened up Rack to check into this at least a little bit, and i don't seem to be having this issue. would you mind sharing a simple barebones patch with the issue on display, or at least a screenshot of your setup?

with the very simple setup in the following screenshot, the signal seems to proceed to the next chosen output on a clock trigger, so it seems to be working as intended on my end.
![image](https://github.com/user-attachments/assets/35d86bd8-aa09-472b-b191-a6f68664489a)

**Comment by pizzathehut893** [comment]
Sorry for the late reply. 
The issue was in fact entirely on my end, as I hadn't yet connected the outputs from expand to my intended sources.  As soon as I did, the switch worked perfectly. 

Thank you for your help! I'm happy it was my dumb mistake so that there's nothing to do.
